<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../EsilvaSoft.KapibaraStudio.Core/EsilvaSoft.KapibaraStudio.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="mongodb-language.v1.json" LogicalName="EsilvaSoft.KapibaraStudio.Autocomplete.Core.mongodb-language.v1.json" />
  </ItemGroup>
</Project>
