<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Jint" />
    <ProjectReference Include="../EsilvaSoft.KapibaraStudio.Application/EsilvaSoft.KapibaraStudio.Application.csproj" />
    <ProjectReference Include="../EsilvaSoft.KapibaraStudio.Infrastructure.System/EsilvaSoft.KapibaraStudio.Infrastructure.System.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" VersionOverride="10.0.10" />
  </ItemGroup>
</Project>
